### ISSUE TITLE
Decimal points issue

### ISSUE THREAD

**Issue by koldirkaev** [mybtcfx/4xbitcoin-V-1.1#1]
https://github.com/mybtcfx/4xbitcoin-V-1.1/blob/master/src/CryptoNoteConfig.h
Line 69
`CRYPTONOTE_DISPLAY_DECIMAL_POINT = 10; `
10? Not 8?

**Comment by mybtcfx** [comment]
10

**Comment by mybtcfx** [comment]
Hello Nikolay Koldirkaev
it is fixed now the decimal point is "8"
